[workspace]
resolver = "2"
members = [
  "beacon-client",
  "beacon-api-types",
  "builder-api-types",
  "builder-client",
  "builder-server",
  "relay-api-types",
  "relay-client",
  "relay-server",
  "common"
]

[workspace.dependencies]
async-trait = "0.1"
axum = { version = "0.8", features = ["ws"] }
bytes = "1.6"
eth2 = { git = "https://github.com/sigp/lighthouse.git", rev = "1e84f6bd93fd626f3252c6e9ff1ed41edb39737d" }
ethereum_serde_utils = "0.7"
ethereum_ssz = "0.7"
ethereum_ssz_derive = "0.7"
flate2 = "1.0"
futures = "0.3.30"
http = "1.2"
mediatype = "0.19.13"
reqwest = { version = "0.12.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1", features = ["raw_value"] }
superstruct = "0.8"
tokio = { version = "1", default-features = false, features = ["signal", "rt-multi-thread"] }
tokio-tungstenite = "0.24.0"
tracing = { version = "0.1", features = ["attributes"] }
types = { git = "https://github.com/sigp/lighthouse.git", rev = "1e84f6bd93fd626f3252c6e9ff1ed41edb39737d" }
rand = "0.8"
